/**
 * Central route registry. The sitemap, llms.txt, footer and internal-link
 * helpers all read from this list so a new page only has to be declared once.
 */

export const routes = [
  {
    path: '/',
    title: 'AI SEO & GEO Automation Platform',
    group: 'product',
    priority: 1,
    changeFrequency: 'weekly',
    summary:
      'An AI agent that researches search opportunities, creates optimized content and builds visibility across Google and AI answer engines.',
  },
  {
    path: '/features',
    title: 'Platform Features',
    group: 'product',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'Every capability in the GetGeoAgent workflow, from research through continuous optimization.',
  },
  {
    path: '/seo-automation',
    title: 'SEO Automation',
    group: 'product',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'Automate keyword research, technical checks, content strategy, internal linking and monitoring.',
  },
  {
    path: '/geo-optimization',
    title: 'GEO Optimization',
    group: 'product',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'Generative Engine Optimization software for visibility inside AI-generated answers.',
  },
  {
    path: '/ai-seo-agent',
    title: 'AI SEO Agent',
    group: 'product',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'How an autonomous SEO agent differs from a traditional SEO tool.',
  },
  {
    path: '/how-it-works',
    title: 'How It Works',
    group: 'product',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'The eight-stage GetGeoAgent loop: discover, understand, plan, create, optimize, publish, measure, improve.',
  },
  {
    path: '/keyword-research',
    title: 'AI Keyword Research',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Expand a seed topic into queries, classify intent and cluster them into pages you can own.',
  },
  {
    path: '/content-planner',
    title: 'Content Planner',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Turn clusters into a sequenced editorial plan with pillars, supporting pieces and refreshes.',
  },
  {
    path: '/ai-content-writer',
    title: 'AI Content Writer',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Research-driven drafts built from a real brief, structured for search and for extraction.',
  },
  {
    path: '/content-optimizer',
    title: 'Content Optimizer',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Find what an existing page is missing against the query it should own, and fix it.',
  },
  {
    path: '/internal-linking',
    title: 'Internal Linking',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Map topical relationships across the site and propose contextual links with real anchors.',
  },
  {
    path: '/seo-audit',
    title: 'SEO Audit',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'A crawl that produces a prioritised list of fixes tied to specific URLs.',
  },
  {
    path: '/technical-seo',
    title: 'Technical SEO',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Crawling, indexing, canonicals, structured data and performance, watched for regressions.',
  },
  {
    path: '/seo-monitoring',
    title: 'SEO Monitoring',
    group: 'product',
    priority: 0.85,
    changeFrequency: 'weekly',
    summary: 'Rankings, page performance and content decay detection, with a short list of next actions.',
  },
  {
    path: '/ai-visibility-tracking',
    title: 'AI Visibility Tracking',
    group: 'product',
    priority: 0.9,
    changeFrequency: 'weekly',
    summary: 'A fixed prompt set checked across AI answer surfaces, recording presence and description.',
  },
  {
    path: '/pricing',
    title: 'Pricing',
    group: 'product',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'How GetGeoAgent plans are structured and what drives cost.',
  },
  {
    path: '/seo-for-saas',
    title: 'SEO for SaaS',
    group: 'solutions',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'Own the problem your product solves and cover the SaaS buying chain from symptom to pricing.',
  },
  {
    path: '/seo-for-agencies',
    title: 'SEO for Agencies',
    group: 'solutions',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'Run one consistent method across many client sites and report movement clients can verify.',
  },
  {
    path: '/seo-for-ecommerce',
    title: 'SEO for Ecommerce',
    group: 'solutions',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'Category depth, product detail, faceted navigation and the buying-guide layer most stores skip.',
  },
  {
    path: '/seo-for-local-business',
    title: 'SEO for Local Businesses',
    group: 'solutions',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'Consistent business details, distinct service and location pages, and answers to what callers ask.',
  },
  {
    path: '/what-is-geo',
    title: 'What is Generative Engine Optimization?',
    group: 'learn',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'A direct, in-depth explanation of GEO, how it works and how it relates to SEO.',
  },
  {
    path: '/seo-vs-geo',
    title: 'SEO vs GEO',
    group: 'learn',
    priority: 0.9,
    changeFrequency: 'monthly',
    summary: 'A side-by-side comparison of search engine optimization and generative engine optimization.',
  },
  {
    path: '/generative-engine-optimization',
    title: 'Generative Engine Optimization',
    group: 'learn',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'The full GEO discipline: entities, structure, citations, authority and measurement.',
  },
  {
    path: '/ai-search-optimization',
    title: 'AI Search Optimization',
    group: 'learn',
    priority: 0.85,
    changeFrequency: 'monthly',
    summary: 'Optimizing for AI Overviews, AI Mode, ChatGPT Search, Gemini, Perplexity and Copilot.',
  },
  {
    path: '/chatgpt-seo',
    title: 'ChatGPT SEO',
    group: 'learn',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'How ChatGPT Search retrieves and cites pages, and what makes content a plausible source.',
  },
  {
    path: '/google-ai-overviews',
    title: 'Google AI Overviews',
    group: 'learn',
    priority: 0.8,
    changeFrequency: 'monthly',
    summary: 'What AI Overviews change, and why conventional SEO still decides eligibility.',
  },
  {
    path: '/google-ai-mode',
    title: 'Google AI Mode',
    group: 'learn',
    priority: 0.75,
    changeFrequency: 'monthly',
    summary: 'Conversational search and why topic coverage matters more than any single page.',
  },
  {
    path: '/gemini-seo',
    title: 'Gemini SEO',
    group: 'learn',
    priority: 0.75,
    changeFrequency: 'monthly',
    summary: 'Optimizing for grounded answers through verifiable, internally consistent content.',
  },
  {
    path: '/perplexity-seo',
    title: 'Perplexity SEO',
    group: 'learn',
    priority: 0.75,
    changeFrequency: 'monthly',
    summary: 'Writing pages whose sentences can be lifted, attributed and still be correct.',
  },
  {
    path: '/resources',
    title: 'Resources',
    group: 'learn',
    priority: 0.7,
    changeFrequency: 'weekly',
    summary: 'Guides, definitions and reference material on SEO, GEO and AI answer engines.',
  },
  {
    path: '/glossary',
    title: 'SEO & GEO Glossary',
    group: 'learn',
    priority: 0.7,
    changeFrequency: 'monthly',
    summary: 'Plain definitions of the SEO, GEO and AI-search terms used across this site.',
  },
  {
    path: '/research',
    title: 'Research',
    group: 'learn',
    priority: 0.6,
    changeFrequency: 'monthly',
    summary: 'The standard any study published here has to meet — method first, findings only when they exist.',
  },
  {
    path: '/blog',
    title: 'Blog',
    group: 'learn',
    priority: 0.7,
    changeFrequency: 'weekly',
    summary: 'Research, guides and product thinking on SEO and generative search.',
  },
  {
    path: '/about',
    title: 'About',
    group: 'company',
    priority: 0.6,
    changeFrequency: 'yearly',
    summary: 'Why GetGeoAgent exists and the principles behind the product.',
  },
  {
    path: '/contact',
    title: 'Contact',
    group: 'company',
    priority: 0.6,
    changeFrequency: 'yearly',
    summary: 'Talk to the GetGeoAgent team.',
  },
  {
    path: '/privacy-policy',
    title: 'Privacy Policy',
    group: 'legal',
    priority: 0.3,
    changeFrequency: 'yearly',
    summary: 'How GetGeoAgent handles personal data.',
  },
  {
    path: '/terms-of-service',
    title: 'Terms of Service',
    group: 'legal',
    priority: 0.3,
    changeFrequency: 'yearly',
    summary: 'The agreement governing use of GetGeoAgent.',
  },
];

export const routeByPath = routes.reduce((acc, route) => {
  acc[route.path] = route;
  return acc;
}, {});

export const routesInGroup = (group) => routes.filter((route) => route.group === group);

export const navigation = {
  product: [
    { label: 'Features', href: '/features' },
    { label: 'SEO Automation', href: '/seo-automation' },
    { label: 'GEO Optimization', href: '/geo-optimization' },
    { label: 'AI SEO Agent', href: '/ai-seo-agent' },
    { label: 'How It Works', href: '/how-it-works' },
  ],
  capabilities: [
    { label: 'Keyword Research', href: '/keyword-research' },
    { label: 'Content Planner', href: '/content-planner' },
    { label: 'AI Content Writer', href: '/ai-content-writer' },
    { label: 'Content Optimizer', href: '/content-optimizer' },
    { label: 'Internal Linking', href: '/internal-linking' },
    { label: 'SEO Audit', href: '/seo-audit' },
    { label: 'Technical SEO', href: '/technical-seo' },
    { label: 'SEO Monitoring', href: '/seo-monitoring' },
    { label: 'AI Visibility Tracking', href: '/ai-visibility-tracking' },
  ],
  solutions: [
    { label: 'SEO for SaaS', href: '/seo-for-saas' },
    { label: 'SEO for Agencies', href: '/seo-for-agencies' },
    { label: 'SEO for Ecommerce', href: '/seo-for-ecommerce' },
    { label: 'SEO for Local Businesses', href: '/seo-for-local-business' },
  ],
  resources: [
    { label: 'What is GEO?', href: '/what-is-geo' },
    { label: 'SEO vs GEO', href: '/seo-vs-geo' },
    { label: 'Generative Engine Optimization', href: '/generative-engine-optimization' },
    { label: 'AI Search Optimization', href: '/ai-search-optimization' },
    { label: 'Blog', href: '/blog' },
    { label: 'Glossary', href: '/glossary' },
    { label: 'Research', href: '/research' },
  ],
  aiSearch: [
    { label: 'ChatGPT SEO', href: '/chatgpt-seo' },
    { label: 'Google AI Overviews', href: '/google-ai-overviews' },
    { label: 'Google AI Mode', href: '/google-ai-mode' },
    { label: 'Gemini SEO', href: '/gemini-seo' },
    { label: 'Perplexity SEO', href: '/perplexity-seo' },
  ],
  company: [
    { label: 'About', href: '/about' },
    { label: 'Contact', href: '/contact' },
  ],
  legal: [
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms of Service', href: '/terms-of-service' },
  ],
};
